{% set version = "0.8.1" %}

package:
  name: cleo
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cleo/cleo-{{ version }}.tar.gz
  sha256: 3d0e22d30117851b45970b6c14aca4ab0b18b1b53c8af57bed13208147e4069f

build:
  number: 0
  noarch: python
  script:
    # we cannot use poetry to install cleo b/c poetry depends on cleo
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    # - poetry >=1.0.0b2
  run:
    - python
    - clikit >=0.4.0,<0.5.0

test:
  imports:
    - cleo
    - cleo.commands
    - cleo.commands.completions
    - cleo.config
    - cleo.io
    - cleo.testers

about:
  home: https://github.com/sdispater/cleo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Cleo allows you to create beautiful and testable command-line interfaces.
  description: Cleo allows you to create beautiful and testable command-line interfaces.
  dev_url: https://github.com/sdispater/cleo

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
