travis:
  secure:
    BINSTAR_TOKEN: iFzupEIVL9oU70MbpxGodGccZ1R7hqmAEQvObX2xHolmiDg2FoJENFkXOeE/k0waHdF95h6kXblfOTOa2zrwMdw2iwx5Bn8PyrMbv3JAupsDQExME7jDBHgUP2XmvH6MsWoEhQuiXmyVasyz+Df6CTGtpUpu4bh4c/mw8ds5hGzbnBSdl1kLhi0xljqDyPFe5CqTLnOSTHhYhALnNHE1wawVeDsGe2uQI/WqKmVT+8pFJLvpy3uriJA9o31Lp9sKqmkByOqWCL0C0UCip17dKsqdH9FicvM8c59S3HaDZVQ+MWti4tyXSP/0ryoAr/TZCCduGXyEZW/MdW3VgoW7c3wguEOsTIsIRAW8HL3mMdjb2Z6aQtYRda7rT4qvT1wu0ablFoV2xUcbSSCJXAPOZKxhvnsRCR2HdbHWZiAVAO5cBQBjZ0E18YVBYcv2HVfzoM/jeDE7NIL8g8cpu7bNEmRlMDtzHIhvjZva8ioR4xpPxTF/2QtiLvCcadVu9xIjp+F3gt+rjtnbUrCiTau/fmUUNpgpOYO2Ogm+mnFOUWrf/ECYqVg6u/miyTYYhsVaE12Ze4uaOyB2m3qzbcYYub2dEbks2XHnuBes0JUs4sqk0PhM0ErEH3qavgHuDZ6Zp4v98bo4eVI97BLHDydqHxC0DyLvC8LF1RBG6xGLmOM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
